FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY cv/requirements.txt .
RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt

COPY . .

ENV MODEL_PATH="models/apple_classifier.pth"
ENV CLASSIFIER_PORT=5000

EXPOSE 5000

CMD ["python", "api/app.py"]
